"""add_provider_and_last_checked_at_to_subscription

Revision ID: 16169376e2ad
Revises: 4e7c3dc52a6e
Create Date: 2026-06-25 15:12:50.675588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16169376e2ad'
down_revision: Union[str, Sequence[str], None] = '4e7c3dc52a6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('provider', sa.String(length=255), nullable=True))
    op.add_column('subscriptions', sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'last_checked_at')
    op.drop_column('subscriptions', 'provider')
    # ### end Alembic commands ###
