"""create_search_runs_table

Revision ID: 35295ee74795
Revises: 16169376e2ad
Create Date: 2026-06-25 15:23:41.991910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '35295ee74795'
down_revision: Union[str, Sequence[str], None] = '16169376e2ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Create Enum explicitly
    search_run_status_enum = postgresql.ENUM('PENDING', 'COMPLETED', 'FAILED', name='search_run_status_enum')
    search_run_status_enum.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subscription_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('external_run_id', sa.String(length=255), nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'COMPLETED', 'FAILED', name='search_run_status_enum', create_type=False), server_default='PENDING', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_runs_external_run_id'), 'search_runs', ['external_run_id'], unique=False)
    op.create_index(op.f('ix_search_runs_subscription_id'), 'search_runs', ['subscription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_runs_subscription_id'), table_name='search_runs')
    op.drop_index(op.f('ix_search_runs_external_run_id'), table_name='search_runs')
    op.drop_table('search_runs')
    # ### end Alembic commands ###

    # 2. Drop Enum
    search_run_status_enum = postgresql.ENUM('PENDING', 'COMPLETED', 'FAILED', name='search_run_status_enum')
    search_run_status_enum.drop(op.get_bind())
