"""add_search_filters_to_subscriptions

Revision ID: 40f6d2b30843
Revises: 561a666d5379
Create Date: 2026-07-14 08:39:16.431504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40f6d2b30843'
down_revision: Union[str, Sequence[str], None] = '561a666d5379'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.add_column('subscriptions', sa.Column('adults', sa.Integer(), server_default='1', nullable=False))
    op.add_column('subscriptions', sa.Column('children', sa.Integer(), server_default='0', nullable=False))
    op.add_column('subscriptions', sa.Column('min_bedrooms', sa.Integer(), nullable=True))
    op.add_column('subscriptions', sa.Column('min_beds', sa.Integer(), nullable=True))
    op.add_column('subscriptions', sa.Column('flexible_days', sa.Integer(), nullable=True))
    op.add_column('subscriptions', sa.Column('max_stops', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'max_stops')
    op.drop_column('subscriptions', 'flexible_days')
    op.drop_column('subscriptions', 'min_beds')
    op.drop_column('subscriptions', 'min_bedrooms')
    op.drop_column('subscriptions', 'children')
    op.drop_column('subscriptions', 'adults')
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    # ### end Alembic commands ###
