"""add_image_url_to_alerts

Revision ID: 4575e68516d9
Revises: 35295ee74795
Create Date: 2026-06-25 22:00:46.831679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4575e68516d9'
down_revision: Union[str, Sequence[str], None] = '35295ee74795'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('image_url', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'image_url')
    # ### end Alembic commands ###
