"""add_deep_link_to_alerts

Revision ID: 561a666d5379
Revises: 4575e68516d9
Create Date: 2026-06-28 06:23:49.942925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '561a666d5379'
down_revision: Union[str, Sequence[str], None] = '4575e68516d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('deep_link', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'deep_link')
    # ### end Alembic commands ###
