"""optimize_indexes

Revision ID: ca5e492b3444
Revises: 1ca4bf70dfa7
Create Date: 2026-05-21 21:46:36.480067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca5e492b3444'
down_revision: Union[str, Sequence[str], None] = '1ca4bf70dfa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_destination'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_is_active'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_max_price'), table_name='subscriptions')
    op.create_index('idx_subscriptions_destination_origin', 'subscriptions', ['destination', 'origin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_subscriptions_destination_origin', table_name='subscriptions')
    op.create_index(op.f('ix_subscriptions_max_price'), 'subscriptions', ['max_price'], unique=False)
    op.create_index(op.f('ix_subscriptions_is_active'), 'subscriptions', ['is_active'], unique=False)
    op.create_index(op.f('ix_subscriptions_destination'), 'subscriptions', ['destination'], unique=False)
    # ### end Alembic commands ###
